"""Remove user_id from reviews

Revision ID: 106c4373cb1c
Revises: c22da265b427
Create Date: 2025-05-05 09:42:08.144357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106c4373cb1c'
down_revision: Union[str, None] = 'c22da265b427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('review_user_id_fkey', 'review', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('review_user_id_fkey', 'review', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
