"""Add Review

Revision ID: 14b64ac84bb8
Revises: 8d3556208804
Create Date: 2025-04-15 16:22:18.832921

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14b64ac84bb8"
down_revision: Union[str, None] = "8d3556208804"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.Integer(), nullable=False),
        sa.Column(
            "review_title", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False
        ),
        sa.Column("review_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("review_date", sa.DateTime(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review")
    # ### end Alembic commands ###
