"""Add Book

Revision ID: 8d3556208804
Revises: 407f4abb5513
Create Date: 2025-04-15 16:00:18.892018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "8d3556208804"
down_revision: Union[str, None] = "407f4abb5513"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "book_title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("book_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("book_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "book_cover_photo",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=True,
        ),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["author.id"],
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_book_book_title"), "book", ["book_title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_book_book_title"), table_name="book")
    op.drop_table("book")
    # ### end Alembic commands ###
