"""Add Discount

Revision ID: ded3d8efc7d6
Revises: 14b64ac84bb8
Create Date: 2025-04-15 16:44:13.495984

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ded3d8efc7d6"
down_revision: Union[str, None] = "14b64ac84bb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discount",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("book_id", sa.BigInteger(), nullable=False),
        sa.Column("discount_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("discount_start_date", sa.Date(), nullable=True),
        sa.Column("discount_end_date", sa.Date(), nullable=True),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["book_id"],
            ["book.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("review", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("review", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "updated_at")
    op.drop_column("review", "created_at")
    op.drop_table("discount")
    # ### end Alembic commands ###
