version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: bookworm-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=bookworm
      - POSTGRES_PASSWORD=bookworm
      - POSTGRES_DB=bookworm
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookworm"]
      interval: 5s
      timeout: 5s
      retries: 5

  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: bookworm-api
  #   volumes:
  #     - .:/app
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DATABASE_URL=postgresql+psycopg://bookworm:bookworm@postgres:5432/bookworm
  #     - JWT_SECRET_KEY=change_this_to_something_secure_in_production
  #     - JWT_ALGORITHM=HS256
  #     - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=30
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres-data: